export interface LocationResponse {
  name?: string,
  locality?: string,
  region?: string,
  metro?: string,
  country?: string,
  continent?: string,
  street_address?: string,
  address_line_2?: string,
  postal_code?: string,
  geo?: string
}

export interface PersonEmailResponse {
  address?: string,
  type?: string,
  first_seen?: string,
  last_seen?: string,
  num_sources?: number
}

export interface PersonExperienceResponse {
  company?: {
    name?: string,
    size?: string,
    id?: string,
    founded?: number,
    industry?: string,
    location?: LocationResponse,
    linkedin_url?: string,
    linkedin_id?: string,
    facebook_url?: string,
    twitter_url?: string,
    website?: string,
    ticker?: string,
    type?: string,
    raw?: Array<string>,
    fuzzy_match?: boolean
  },
  location_names?: Array<string>,
  end_date?: string,
  start_date?: string,
  title?: {
    name?: string,
    role?: string,
    sub_role?: string,
    levels?: Array<string>,
    raw?: Array<string>,
  },
  is_primary?: boolean,
  summary?: string,
  first_seen?: string,
  last_seen?: string
}

export interface PersonEducationResponse {
  school?: {
    name?: string,
    type?: string,
    id?: string,
    location?: LocationResponse,
    linkedin_url?: string,
    facebook_url?: string,
    twitter_url?: string,
    linkedin_id?: string,
    website?: string,
    domain?: string,
    raw?: Array<string>
  },
  end_date?: string,
  start_date?: string,
  gpa?: string,
  degrees?: Array<string>,
  majors?: Array<string>,
  minors?: Array<string>,
  raw?: Array<string>
  summary?: string
}

export interface PersonProfileResponse {
  network?: string,
  id?: string,
  url?: string,
  username?: string,
  first_seen?: string,
  last_seen?: string,
  num_sources?: number
}

export interface PersonPhoneResponse {
  number?: string,
  first_seen?: string,
  last_seen?: string,
  num_sources?: number
}

export interface PersonStreetAddressResponse {
  street_address?: string,
  address_line_2?: string,
  name?: string,
  locality?: string,
  metro?: string,
  region?: string,
  postal_code?: string,
  country?: string,
  geo?: string,
  continent?: string,
  first_seen?: string,
  last_seen?: string,
  num_sources?: number
}

export interface PersonCertificateResponse {
  start_date?: string,
  end_date?: string,
  name?: string,
  organization?: string
}

export interface PersonBirthdateResponse {
  month?: string,
  day?: string,
  year?: string
}

export interface PersonLanguageResponse {
  name?: string,
  proficiency?: number
}

export interface PersonJobHistoryResponse {
  company_id?: string,
  company_name?: string,
  title?: string,
  first_seen?: string,
  last_seen?: string,
  num_sources?: number
}

export interface PersonResponse {
  id?: string,
  full_name?: string,
  first_name?: string,
  middle_initial?: string,
  middle_name?: string,
  last_initial?: string,
  last_name?: string,
  gender?: string,
  birth_year?: string,
  birth_date?: string,
  linkedin_url?: string,
  linkedin_username?: string,
  linkedin_id?: string,
  facebook_url?: string,
  facebook_username?: string,
  facebook_id?: string,
  twitter_url?: string,
  twitter_username?: string,
  github_url?: string,
  github_username?: string,
  work_email?: string,
  personal_emails?: Array<string>,
  mobile_phone?: string,
  industry?: string,
  job_title?: string,
  job_title_role?: string,
  job_title_sub_role?: string,
  job_title_levels?: Array<string>,
  job_company_id?: string,
  job_company_name?: string,
  job_company_website?: string,
  job_company_size?: string,
  job_company_founded?: number,
  job_company_industry?: string,
  job_company_linkedin_url?: string,
  job_company_linkedin_id?: string,
  job_company_facebook_url?: string,
  job_company_twitter_url?: string,
  job_company_location_name?: string,
  job_company_location_locality?: string,
  job_company_location_metro?: string,
  job_company_location_region?: string,
  job_company_location_geo?: string,
  job_company_location_street_address?: string,
  job_company_location_address_line_2?: string,
  job_company_location_postal_code?: string,
  job_company_location_country?: string,
  job_company_location_continent?: string,
  job_company_ticker?: string,
  job_company_type?: string,
  job_onet_code?: string,
  job_onet_major_group?: string,
  job_onet_minor_group?: string,
  job_onet_broad_occupation?: string,
  job_onet_specific_occupation?: string,
  job_onet_title?: string,
  job_summary?: string,
  job_last_updated?: string,
  job_start_date?: string,
  languages?: Array<PersonLanguageResponse>,
  location_name?: string,
  location_locality?: string,
  location_metro?: string,
  location_region?: string,
  location_country?: string,
  location_continent?: string,
  location_street_address?: string,
  location_address_line_2?: string,
  location_postal_code?: string,
  location_geo?: string,
  location_last_updated?: string,
  linkedin_connections?: number,
  inferred_salary?: string,
  inferred_years_experience?: number,
  summary?: string,
  phone_numbers?: Array<string>,
  emails?: Array<PersonEmailResponse>,
  interests?: Array<string>,
  skills?: Array<string>,
  location_names?: Array<string>,
  regions?: Array<string>,
  countries?: Array<string>,
  street_addresses?: Array<PersonStreetAddressResponse>,
  experience?: Array<PersonExperienceResponse>,
  education?: Array<PersonEducationResponse>,
  profiles?: Array<PersonProfileResponse>,
  phones?: Array<PersonPhoneResponse>,
  facebook_friends?: number,
  name_aliases?: Array<string>,
  possible_emails?: Array<PersonEmailResponse>,
  possible_phones?: Array<PersonPhoneResponse>,
  possible_profiles?: Array<PersonProfileResponse>,
  possible_street_addresses?: Array<PersonStreetAddressResponse>,
  possible_birth_dates?: Array<PersonBirthdateResponse>,
  possible_location_names?: Array<string>,
  job_history?: Array<PersonJobHistoryResponse>,
  num_records?: number,
  num_sources?: number,
  first_seen?: string,
  certifications?: Array<PersonCertificateResponse>
}

export interface CompanyResponse {
  name?: string,
  size?: string,
  employee_count?: number,
  id?: string,
  founded?: number,
  industry?: string,
  location?: LocationResponse,
  linkedin_id?: string,
  linkedin_url?: string,
  facebook_url?: string,
  twitter_url?: string,
  profiles?: Array<string>,
  website?: string,
  ticker?: string,
  type?: string,
  summary?: string,
  tags?: Array<string>,
  headline?: null,
  alternative_names?: Array<string>,
  alternative_domains?: Array<string>,
  affiliated_profiles?: Array<string>,
  likelihood?: number,
  average_employee_tenure?: number,
  average_tenure_by_level?: {
    cxo?: number,
    director?: number,
    entry?: number,
    manager?: number,
    owner?: number,
    partner?: number,
    senior?: number,
    training?: number,
    unpaid?: number,
    vp?: number,
  },
  average_tenure_by_role?: {
    customer_service?: number,
    design?: number,
    education?: number,
    engineering?: number,
    finance?: number,
    health?: number,
    human_resources?: number,
    legal?: number,
    marketing?: number,
    media?: number,
    operations?: number,
    public_relations?: number,
    real_estate?: number,
    sales?: number,
    trades?: number,
  },
  employee_count_by_country?: {
    afghanistan?: number,
    albania ?: number,
    algeria ?: number,
    'american samoa' ?: number,
    andorra ?: number,
    angola ?: number,
    anguilla ?: number,
    antarctica ?: number,
    'antigua and barbuda' ?: number,
    argentina ?: number,
    armenia ?: number,
    aruba ?: number,
    australia?: number,
    austria?: number,
    azerbaijan?: number,
    bahamas?: number,
    bahrain?: number,
    bangladesh?: number,
    barbados?: number,
    belarus?: number,
    belgium?: number,
    belize?: number,
    benin?: number,
    bermuda?: number,
    bhutan?: number,
    bolivia?: number,
    'bosnia and herzegovina'?: number,
    botswana?: number,
    'bouvet island'?: number,
    brazil?: number,
    'british indian ocean territory'?: number,
    'british virgin islands'?: number,
    brunei?: number,
    bulgaria?: number,
    'burkina faso'?: number,
    burundi?: number,
    cambodia?: number,
    cameroon?: number,
    canada?: number,
    'cape verde'?: number,
    'caribbean netherlands'?: number,
    'cayman islands'?: number,
    'central african republic'?: number,
    chad?: number,
    chile?: number,
    china?: number,
    'christmas island'?: number,
    'cocos (keeling) islands'?: number,
    colombia?: number,
    comoros?: number,
    'cook islands'?: number,
    'costa rica'?: number,
    croatia?: number,
    cuba?: number,
    curaçao?: number,
    cyprus?: number,
    czechia?: number,
    'côte d’ivoire'?: number,
    'democratic republic of the congo'?: number,
    denmark?: number,
    djibouti?: number,
    dominica?: number,
    'dominican republic'?: number,
    ecuador?: number,
    egypt?: number,
    'el salvador'?: number,
    'equatorial guinea'?: number,
    eritrea?: number,
    estonia?: number,
    ethiopia?: number,
    'falkland islands'?: number,
    'faroe islands'?: number,
    fiji?: number,
    finland?: number,
    france?: number,
    'french guiana'?: number,
    'french polynesia'?: number,
    'french southern territories'?: number,
    gabon?: number,
    gambia?: number,
    georgia?: number,
    germany?: number,
    ghana?: number,
    gibraltar?: number,
    greece?: number,
    greenland?: number,
    grenada?: number,
    guadeloupe?: number,
    guam?: number,
    guatemala?: number,
    guernsey?: number,
    guinea?: number,
    'guinea-bissau'?: number,
    guyana?: number,
    haiti?: number,
    'heard island and mcdonald islands'?: number,
    honduras?: number,
    'hong kong'?: number,
    hungary?: number,
    iceland?: number,
    india?: number,
    indonesia?: number,
    iran?: number,
    iraq?: number,
    ireland?: number,
    'isle of man'?: number,
    israel?: number,
    italy?: number,
    'ivory coast'?: number,
    jamaica?: number,
    japan?: number,
    jersey?: number,
    jordan?: number,
    kazakhstan?: number,
    kenya?: number,
    kiribati?: number,
    kosovo?: number,
    kuwait?: number,
    kyrgyzstan?: number,
    laos?: number,
    latvia?: number,
    lebanon?: number,
    lesotho?: number,
    liberia?: number,
    libya?: number,
    liechtenstein?: number,
    lithuania?: number,
    luxembourg?: number,
    macau?: number,
    macedonia?: number,
    madagascar?: number,
    malawi?: number,
    malaysia?: number,
    maldives?: number,
    mali?: number,
    malta?: number,
    'marshall islands'?: number,
    martinique?: number,
    mauritania?: number,
    mauritius?: number,
    mayotte?: number,
    mexico?: number,
    micronesia?: number,
    moldova?: number,
    monaco?: number,
    mongolia?: number,
    montenegro?: number,
    montserrat?: number,
    morocco?: number,
    mozambique?: number,
    myanmar?: number,
    namibia?: number,
    nauru?: number,
    nepal?: number,
    netherlands?: number,
    'netherlands antilles'?: number,
    'new caledonia'?: number,
    'new zealand'?: number,
    nicaragua?: number,
    niger?: number,
    nigeria?: number,
    niue?: number,
    'norfolk island'?: number,
    'north korea'?: number,
    'northern mariana islands'?: number,
    norway?: number,
    oman?: number,
    pakistan?: number,
    palau?: number,
    palestine?: number,
    panama?: number,
    'papua new guinea'?: number,
    paraguay?: number,
    peru?: number,
    philippines?: number,
    pitcairn?: number,
    poland?: number,
    portugal?: number,
    'puerto rico'?: number,
    qatar?: number,
    'republic of the congo'?: number,
    romania?: number,
    russia?: number,
    rwanda?: number,
    réunion?: number,
    'saint barthélemy'?: number,
    'saint helena'?: number,
    'saint kitts and nevis'?: number,
    'saint lucia'?: number,
    'saint martin'?: number,
    'saint pierre and miquelon'?: number,
    'saint vincent and the grenadines'?: number,
    samoa?: number,
    'san marino'?: number,
    'saudi arabia'?: number,
    senegal?: number,
    serbia?: number,
    seychelles?: number,
    'sierra leone'?: number,
    singapore?: number,
    'sint maarten'?: number,
    slovakia?: number,
    slovenia?: number,
    'solomon islands'?: number,
    somalia?: number,
    'south africa'?: number,
    'south georgia and the south sandwich islands'?: number,
    'south korea'?: number,
    'south sudan'?: number,
    spain?: number,
    'sri lanka'?: number,
    sudan?: number,
    suriname?: number,
    'svalbard and jan mayen'?: number,
    swaziland?: number,
    sweden?: number,
    switzerland?: number,
    syria?: number,
    'são tomé and príncipe'?: number,
    taiwan?: number,
    tajikistan?: number,
    tanzania?: number,
    thailand?: number,
    'timor-leste'?: number,
    togo?: number,
    tokelau?: number,
    tonga?: number,
    'trinidad and tobago'?: number,
    tunisia?: number,
    'turkey' ?: number,
    'turkmenistan'?: number,
    'turks and caicos islands'?: number,
    tuvalu?: number,
    'u.s. virgin islands'?: number,
    uganda?: number,
    ukraine?: number,
    'united arab emirates'?: number,
    'united kingdom'?: number,
    'united states'?: number,
    'united states minor outlying islands'?: number,
    uruguay?: number,
    uzbekistan?: number,
    vanuatu?: number,
    'vatican city'?: number,
    venezuela?: number,
    vietnam?: number,
    'wallis and futuna'?: number,
    'western sahara'?: number,
    yemen?: number,
    zambia?: number,
    zimbabwe?: number,
    'Åland islands'?: number,
    'åland islands'?: number,
  },
  employee_count_by_month?: object,
  employee_count_by_month_by_level?: object,
  employee_count_by_month_by_role?: object,
  employee_churn_rate: {
    '3_month'?: number,
    '6_month'?: number,
    '12_month'?: number,
    '24_month'?: number,
  },
  employee_growth_rate?: {
    '3_month'?: number,
    '6_month'?: number,
    '12_month'?: number,
    '24_month'?: number,
  },
  gross_additions_by_month?: object,
  gross_departures_by_month?: object,
  inferred_revenue?: '$0-$1M' | '$1M-$10M' | '$10M-$25M' | '$25M-$50M' | '$50M-$100M' | '$100M-$250M' | '$250M-$500M' | '$500M-$1B' | '$1B-$10B' | '$10B+',
  recent_exec_departures?: Array<{
    departed_date?: string,
    pdl_id?: string,
    job_title?: string,
    job_title_role?: 'customer_service' | 'design' | 'education' | 'engineering' | 'finance' | 'health' | 'human_resources' | 'legal' | 'marketing' | 'media' | 'operations' | 'public_relations' | 'real_estate' | 'sales' | 'trades',
    job_title_sub_role?: 'accounting' | 'accounts' | 'brand_marketing' | 'broadcasting' | 'business_development' | 'compensation' | 'content_marketing' | 'customer_success' | 'data' | 'dental' | 'devops' | 'doctor' | 'editorial' | 'education_administration' | 'electrical' | 'employee_development' | 'events' | 'fitness' | 'graphic_design' | 'information_technology' | 'investment' | 'journalism' | 'judicial' | 'lawyer' | 'logistics' | 'mechanical' | 'media_relations' | 'network' | 'nursing' | 'office_management' | 'paralegal' | 'pipeline' | 'product' | 'product_design' | 'product_marketing' | 'professor' | 'project_engineering' | 'project_management' | 'property_management' | 'quality_assurance' | 'realtor' | 'recruiting' | 'researcher' | 'security' | 'software' | 'support' | 'systems' | 'tax' | 'teacher' | 'therapy' | 'video' | 'web' | 'web_design' | 'wellness' | 'writing',
    job_title_levels?: Array<'cxo' | 'director' | 'entry' | 'manager' | 'owner' | 'partner' | 'senior' | 'training' | 'unpaid' | 'vp'>,
    new_company_id?: string,
    new_company_job_title?: string,
    new_company_job_title_role?: 'customer_service' | 'design' | 'education' | 'engineering' | 'finance' | 'health' | 'human_resources' | 'legal' | 'marketing' | 'media' | 'operations' | 'public_relations' | 'real_estate' | 'sales' | 'trades',
    new_company_job_title_sub_role?: 'accounting' | 'accounts' | 'brand_marketing' | 'broadcasting' | 'business_development' | 'compensation' | 'content_marketing' | 'customer_success' | 'data' | 'dental' | 'devops' | 'doctor' | 'editorial' | 'education_administration' | 'electrical' | 'employee_development' | 'events' | 'fitness' | 'graphic_design' | 'information_technology' | 'investment' | 'journalism' | 'judicial' | 'lawyer' | 'logistics' | 'mechanical' | 'media_relations' | 'network' | 'nursing' | 'office_management' | 'paralegal' | 'pipeline' | 'product' | 'product_design' | 'product_marketing' | 'professor' | 'project_engineering' | 'project_management' | 'property_management' | 'quality_assurance' | 'realtor' | 'recruiting' | 'researcher' | 'security' | 'software' | 'support' | 'systems' | 'tax' | 'teacher' | 'therapy' | 'video' | 'web' | 'web_design' | 'wellness' | 'writing',
    new_company_job_title_levels?: Array<'cxo' | 'director' | 'entry' | 'manager' | 'owner' | 'partner' | 'senior' | 'training' | 'unpaid' | 'vp'>,
  }>,
  recent_exec_hires?: Array<{
    joined_date?: string,
    pdl_id?: string,
    job_title?: string,
    job_title_role?: 'customer_service' | 'design' | 'education' | 'engineering' | 'finance' | 'health' | 'human_resources' | 'legal' | 'marketing' | 'media' | 'operations' | 'public_relations' | 'real_estate' | 'sales' | 'trades',
    job_title_sub_role?: 'accounting' | 'accounts' | 'brand_marketing' | 'broadcasting' | 'business_development' | 'compensation' | 'content_marketing' | 'customer_success' | 'data' | 'dental' | 'devops' | 'doctor' | 'editorial' | 'education_administration' | 'electrical' | 'employee_development' | 'events' | 'fitness' | 'graphic_design' | 'information_technology' | 'investment' | 'journalism' | 'judicial' | 'lawyer' | 'logistics' | 'mechanical' | 'media_relations' | 'network' | 'nursing' | 'office_management' | 'paralegal' | 'pipeline' | 'product' | 'product_design' | 'product_marketing' | 'professor' | 'project_engineering' | 'project_management' | 'property_management' | 'quality_assurance' | 'realtor' | 'recruiting' | 'researcher' | 'security' | 'software' | 'support' | 'systems' | 'tax' | 'teacher' | 'therapy' | 'video' | 'web' | 'web_design' | 'wellness' | 'writing',
    job_title_levels?: Array<'cxo' | 'director' | 'entry' | 'manager' | 'owner' | 'partner' | 'senior' | 'training' | 'unpaid' | 'vp'>,
    previous_company_id?: string,
    previous_company_job_title?: string,
    previous_company_job_title_role?: 'customer_service' | 'design' | 'education' | 'engineering' | 'finance' | 'health' | 'human_resources' | 'legal' | 'marketing' | 'media' | 'operations' | 'public_relations' | 'real_estate' | 'sales' | 'trades',
    previous_company_job_title_sub_role?: 'accounting' | 'accounts' | 'brand_marketing' | 'broadcasting' | 'business_development' | 'compensation' | 'content_marketing' | 'customer_success' | 'data' | 'dental' | 'devops' | 'doctor' | 'editorial' | 'education_administration' | 'electrical' | 'employee_development' | 'events' | 'fitness' | 'graphic_design' | 'information_technology' | 'investment' | 'journalism' | 'judicial' | 'lawyer' | 'logistics' | 'mechanical' | 'media_relations' | 'network' | 'nursing' | 'office_management' | 'paralegal' | 'pipeline' | 'product' | 'product_design' | 'product_marketing' | 'professor' | 'project_engineering' | 'project_management' | 'property_management' | 'quality_assurance' | 'realtor' | 'recruiting' | 'researcher' | 'security' | 'software' | 'support' | 'systems' | 'tax' | 'teacher' | 'therapy' | 'video' | 'web' | 'web_design' | 'wellness' | 'writing',
    previous_company_job_title_levels?: Array<'cxo' | 'director' | 'entry' | 'manager' | 'owner' | 'partner' | 'senior' | 'training' | 'unpaid' | 'vp'>,
  }>,
  top_next_employers_by_role?: {
    customer_service?: object,
    design?: object,
    education?: object,
    engineering?: object,
    finance?: object,
    health?: object,
    human_resources?: object,
    legal?: object,
    marketing?: object,
    media?: object,
    operations?: object,
    public_relations?: object,
    real_estate?: object,
    sales?: object,
    trades?: object,
  },
  top_previous_employers_by_role?: {
    customer_service?: object,
    design?: object,
    education?: object,
    engineering?: object,
    finance?: object,
    health?: object,
    human_resources?: object,
    legal?: object,
    marketing?: object,
    media?: object,
    operations?: object,
    public_relations?: object,
    real_estate?: object,
    sales?: object,
    trades?: object,
  },
  top_us_employee_metros: object,
  all_subsidiaries?: Array<string>,
  direct_subsidiaries?: Array<string>,
  immediate_parent?: string,
  ultimate_parent?: string,
}

export interface ErrorResponse {
  message: string,
  status?: number
}
